name: statsfm
description: Official stats.fm Dart package
version: 1.3.4
homepage: https://github.com/statsfm/statsfm.dart

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  json_annotation: ^4.4.0
  hive_generator: 2.0.0
  dio: 4.0.6
  dio_http_cache: ^0.3.0

dependency_overrides:
  json_serializable: ^6.1.4

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
